
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class VentanaReportes extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo; // Modelo para la tabla
    
    private ArrayList<Clase> clases; // Lista de clases disponibles
    private Usuario usuario; // Usuario actual

    public VentanaReportes(ArrayList<Clase> clases, Usuario usuario) {
        super("Generación de Reportes", true, true, true, true);
        this.clases = clases;
        this.usuario = usuario;

        initComponents(); // Inicializar componentes gráficos
        inicializarModelo(); // Vincular el modelo con la tabla
        cargarDatos(); // Cargar los datos en la tabla
    }

    private void inicializarModelo() {
        // Inicializar el modelo de la tabla
        modelo = new DefaultTableModel(new String[]{"Estudiante", "Clase", "Nota Final"}, 0) {
        };

        // Configurar la tabla con el modelo
        tablaReportes.setModel(modelo); // Ahora tablaReportes estará inicializada
    }

    private void cargarDatos() {
        // Limpia los datos actuales de la tabla
        modelo.setRowCount(0);

        // Recorrer las clases y generar los reportes
        for (Clase clase : clases) {
            if (usuario.getPerfil().equals("Profesor") && !clase.getProfesor().equals(usuario)) {
                continue; // Mostrar solo clases del profesor actual
            }
            for (Estudiante estudiante : clase.getEstudiantes()) {
                Nota nota = clase.obtenerNotas(estudiante);
                modelo.addRow(new Object[]{
                    estudiante.getNombre(),
                    clase.getNombre(),
                    nota != null ? nota.calcularNotaFinal() : "Sin notas"
                });
            }
        }

        // Notificar al usuario si no hay datos para mostrar
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos disponibles para generar reportes.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Generación Reportes");

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables
}
