import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class VentanaClases extends javax.swing.JInternalFrame {

    public VentanaClases(ArrayList<Clase> clases, String perfilUsuario) {
        super("Ver Clases", true, true, true, true);
        initComponents();
                
        setLayout(new BorderLayout());

        String[] columnas = perfilUsuario.equals("Profesor") ?
            new String[]{"Código", "Nombre", "Estudiantes"} :
            new String[]{"Código", "Nombre", "Profesor"};

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (Clase clase : clases) {
            if (perfilUsuario.equals("Profesor")) {
                modelo.addRow(new Object[]{
                    clase.getCodigo(),
                    clase.getNombre(),
                    clase.getEstudiantes().size() + " estudiantes"
                });
            } else {
                modelo.addRow(new Object[]{
                    clase.getCodigo(),
                    clase.getNombre(),
                    clase.getProfesor().getNombre()
                });
            }
        }

        tablaClases = new JTable(modelo);
        JScrollPane scrollPane = new JScrollPane(tablaClases);

        add(scrollPane, BorderLayout.CENTER);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClases = new javax.swing.JTable();

        setClosable(true);
        setTitle("Gestión de Clases");

        tablaClases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Estudiantes"
            }
        ));
        jScrollPane1.setViewportView(tablaClases);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClases;
    // End of variables declaration//GEN-END:variables
}
