
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class VentanaPrincipal extends javax.swing.JFrame {

    private Usuario usuario;
    private BaseDeDatos baseDeDatos;

    public VentanaPrincipal(Usuario usuario, BaseDeDatos baseDeDatos) {
        initComponents();
        this.usuario = usuario;
        this.baseDeDatos = baseDeDatos;

        // Configuración dinámica según el perfil del usuario
        if (usuario.getPerfil().equals("Estudiante")) {
            MenuNotas.setEnabled(false); // Estudiantes no pueden registrar notas
        }

        configurarBarraInferior();
    }

    private void abrirVentanaInterna(JInternalFrame ventana) {
        desktopPane.add(ventana);
        ventana.setVisible(true);
    }

    private void configurarBarraInferior() {
        // Establecer la hora y usuario inicial
        actualizarBarraInferior();

        Timer timer = new Timer(1000, e -> actualizarBarraInferior());
        timer.start();
    }

    private void actualizarBarraInferior() {
        // Obtener la fecha y hora actual
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaHoraActual = sdf.format(new Date());

        // Actualizar el texto del JLabel
        lblUsuario.setText("Usuario: " + usuario.getNombre() + "    | Tipo: " + usuario.getPerfil());
        lblhora.setText(fechaHoraActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuClases = new javax.swing.JMenu();
        MenuVerClases = new javax.swing.JMenuItem();
        MenuAsignaturas = new javax.swing.JMenu();
        MenuGestionarAsignaturas = new javax.swing.JMenuItem();
        MenuNotas = new javax.swing.JMenu();
        MenuRegistrarNotas = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        MenuGenerarReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblUsuario.setText(" ");

        lblhora.setText(" ");
        lblhora.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblhora)
                    .addComponent(btnCerrarSesion))
                .addContainerGap())
        );

        MenuClases.setText("Clases");

        MenuVerClases.setText("Ver Clases");
        MenuVerClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerClasesActionPerformed(evt);
            }
        });
        MenuClases.add(MenuVerClases);

        jMenuBar1.add(MenuClases);

        MenuAsignaturas.setText("Asignaturas");

        MenuGestionarAsignaturas.setText("Gestionar Asignaturas");
        MenuGestionarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGestionarAsignaturasActionPerformed(evt);
            }
        });
        MenuAsignaturas.add(MenuGestionarAsignaturas);

        jMenuBar1.add(MenuAsignaturas);

        MenuNotas.setText("Notas");

        MenuRegistrarNotas.setText("Registrar Notas");
        MenuRegistrarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarNotasActionPerformed(evt);
            }
        });
        MenuNotas.add(MenuRegistrarNotas);

        jMenuBar1.add(MenuNotas);

        MenuReportes.setText("Reportes");
        MenuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReportesActionPerformed(evt);
            }
        });

        MenuGenerarReportes.setText("Generar Reportes");
        MenuGenerarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGenerarReportesActionPerformed(evt);
            }
        });
        MenuReportes.add(MenuGenerarReportes);

        jMenuBar1.add(MenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuVerClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerClasesActionPerformed
        abrirVentanaInterna(new VentanaClases(baseDeDatos.getClases(), usuario.getPerfil()));

    }//GEN-LAST:event_MenuVerClasesActionPerformed

    private void MenuGestionarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestionarAsignaturasActionPerformed
        abrirVentanaInterna(new VentanaAsignaturas(baseDeDatos));
    }//GEN-LAST:event_MenuGestionarAsignaturasActionPerformed

    private void MenuRegistrarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarNotasActionPerformed
        if (usuario.getPerfil().equals("Profesor")) {
            abrirVentanaInterna(new VentanaRegistrarNotas(baseDeDatos, usuario));
        } else {
            JOptionPane.showMessageDialog(this, "Solo los profesores pueden registrar notas.", "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_MenuRegistrarNotasActionPerformed

    private void MenuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReportesActionPerformed
        
    }//GEN-LAST:event_MenuReportesActionPerformed

    private void MenuGenerarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGenerarReportesActionPerformed
        abrirVentanaInterna(new VentanaReportes(baseDeDatos.getClases(), usuario));
    }//GEN-LAST:event_MenuGenerarReportesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de que desea cerrar sesión?",
        "Cerrar Sesión",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    // Verificar la respuesta del usuario
    if (opcion == JOptionPane.YES_OPTION) {
        // Cerrar la ventana principal
        this.dispose();

        // Abrir la ventana de inicio de sesión (VentanaLogin)
          VentanaLogin ventanaLogin = new VentanaLogin(); // Pasa los datos necesarios si aplica
            ventanaLogin.setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BaseDeDatos baseDeDatos = new BaseDeDatos();
                Usuario profesor = baseDeDatos.getProfesores().get(0); // Profesor de prueba
                new VentanaPrincipal(profesor, baseDeDatos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAsignaturas;
    private javax.swing.JMenu MenuClases;
    private javax.swing.JMenuItem MenuGenerarReportes;
    private javax.swing.JMenuItem MenuGestionarAsignaturas;
    private javax.swing.JMenu MenuNotas;
    private javax.swing.JMenuItem MenuRegistrarNotas;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenuItem MenuVerClases;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblhora;
    // End of variables declaration//GEN-END:variables
}
